name: kantin_bu_rom
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.8+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.10.0
  google_fonts: ^6.2.1
  url_launcher: ^6.3.1


  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.3

flutter:

  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
